import type { RegCheckRawData } from './regcheck';

export const RegCheckDemoData: Record<string, RegCheckRawData> = {
  FE120KD: {
    Description: 'Mazda CX-3',
    RegistrationYear: '2016',
    CarMake: { CurrentTextValue: 'Mazda' },
    CarModel: { CurrentTextValue: 'CX-3' },
    EngineSize: { CurrentTextValue: '' },
    FuelType: { CurrentTextValue: '' },
    NumberOfDoors: '5',
    Version: 'CX-3 1.5d Evolve 2wd 105cv',
    BodyStyle: { CurrentTextValue: 'SUV' },
    Vin: 'JMZDK6WS610157548',
    PowerCV: '0',
    ImageUrl: 'https://www.targa.co.it/image.aspx/@TWF6ZGEgQ1gtMw==',
  },
  AB123CD: {
    Description: 'Fiat 500',
    RegistrationYear: '2018',
    CarMake: { CurrentTextValue: 'Fiat' },
    CarModel: { CurrentTextValue: '500' },
    EngineSize: { CurrentTextValue: '' },
    FuelType: { CurrentTextValue: 'Benzina' },
    NumberOfDoors: '3',
    Version: '500 1.2 Lounge 69cv',
    BodyStyle: { CurrentTextValue: 'Berlina' },
    PowerCV: '69',
    ImageUrl: '',
  },
  EF456GH: {
    Description: 'Volkswagen Golf',
    RegistrationYear: '2019',
    CarMake: { CurrentTextValue: 'Volkswagen' },
    CarModel: { CurrentTextValue: 'Golf' },
    EngineSize: { CurrentTextValue: '1.6 TDI' },
    FuelType: { CurrentTextValue: 'Diesel' },
    NumberOfDoors: '5',
    Version: 'Golf VII 1.6 TDI Highline 115cv',
    BodyStyle: { CurrentTextValue: 'Berlina' },
    PowerCV: '115',
    ImageUrl: '',
  },
  CD789EF: {
    Description: 'BMW Serie 1',
    RegistrationYear: '2020',
    CarMake: { CurrentTextValue: 'BMW' },
    CarModel: { CurrentTextValue: 'Serie 1' },
    EngineSize: { CurrentTextValue: '' },
    FuelType: { CurrentTextValue: 'Diesel' },
    NumberOfDoors: '5',
    Version: '118d MSport 150cv',
    BodyStyle: { CurrentTextValue: 'Berlina' },
    PowerCV: '150',
    ImageUrl: '',
  },
  GH012IL: {
    Description: 'Toyota Yaris',
    RegistrationYear: '2021',
    CarMake: { CurrentTextValue: 'Toyota' },
    CarModel: { CurrentTextValue: 'Yaris' },
    EngineSize: { CurrentTextValue: '' },
    FuelType: { CurrentTextValue: 'Ibrida' },
    NumberOfDoors: '5',
    Version: 'Yaris 1.5 Hybrid Active 116cv',
    BodyStyle: { CurrentTextValue: 'Berlina' },
    PowerCV: '116',
    ImageUrl: '',
  },
};
