/**
 * Build script to generate apps/web/src/lib/guides-articoli.ts
 * from the 4 article data modules (36 total articles).
 *
 * Usage: node scripts/build_guides_articoli.mjs
 */

import { ARTICLES_VALUTAZIONE } from './articles_data_valutazione.mjs';
import { ARTICLES_ACQUISTO } from './articles_data_acquisto.mjs';
import { ARTICLES_VENDITA } from './articles_data_vendita.mjs';
import { ARTICLES_MECCANICA } from './articles_data_meccanica.mjs';
import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const allArticles = [
  ...ARTICLES_VALUTAZIONE,
  ...ARTICLES_ACQUISTO,
  ...ARTICLES_VENDITA,
  ...ARTICLES_MECCANICA,
];

console.log(`Total articles: ${allArticles.length}`);

// Build the TypeScript source
const guides = allArticles.map(article => {
  const readMinutes = Math.max(6, Math.ceil(
    article.sections.reduce((acc, s) => {
      const pLen = (s.paragraphs || []).join(' ').length;
      const lLen = (s.list || []).join(' ').length;
      return acc + pLen + lLen;
    }, 0) / 1200 // ~1200 chars per minute reading speed
  ));

  return {
    slug: article.slug,
    title: article.title,
    description: article.description,
    published: article.published,
    category: article.category,
    cta: article.cta,
    image: `/images/guide/${article.slug}.jpg`,
    readTime: `${readMinutes} min`,
    featured: false,
    sections: article.sections,
  };
});

const tsContent = `/**
 * ============================================================================
 * AUTOESPERTO - 36 NEW ARTICLE GUIDES (GENERATED - DO NOT EDIT MANUALLY)
 * ============================================================================
 * Generated by scripts/build_guides_articoli.mjs
 * Categories: valutazione (${ARTICLES_VALUTAZIONE.length}), acquisto (${ARTICLES_ACQUISTO.length}), vendita (${ARTICLES_VENDITA.length}), affidabilita (${ARTICLES_MECCANICA.length})
 * Total: ${allArticles.length} guides
 * ============================================================================
 */

import type { Guide } from './guide-types';

export const articoliGuides: Guide[] = ${JSON.stringify(guides, null, 2)};
`;

const outPath = join(__dirname, '..', 'apps', 'web', 'src', 'lib', 'guides-articoli.ts');
writeFileSync(outPath, tsContent, 'utf8');
console.log(`Written ${guides.length} guides to ${outPath}`);
console.log('Categories breakdown:');
const cats = {};
guides.forEach(g => { cats[g.category] = (cats[g.category] || 0) + 1; });
Object.entries(cats).forEach(([k, v]) => console.log(`  ${k}: ${v}`));
