from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'output' / 'pdf' / 'autoesperto-funding-pitch.pdf'
OUT.parent.mkdir(parents=True, exist_ok=True)
navy=colors.HexColor('#0b172a'); blue=colors.HexColor('#1d74f5'); cyan=colors.HexColor('#20c4d9'); ink=colors.HexColor('#172033'); muted=colors.HexColor('#667085'); light=colors.HexColor('#eef4fb')
s=getSampleStyleSheet(); s.add(ParagraphStyle(name='CoverTitle',parent=s['Title'],fontName='Helvetica-Bold',fontSize=31,leading=35,textColor=colors.white,spaceAfter=10)); s.add(ParagraphStyle(name='CoverSub',parent=s['Normal'],fontSize=14,leading=19,textColor=colors.HexColor('#c9dcf4'))); s.add(ParagraphStyle(name='H',parent=s['Heading1'],fontName='Helvetica-Bold',fontSize=22,leading=27,textColor=navy,spaceAfter=10)); s.add(ParagraphStyle(name='Kicker',parent=s['Normal'],fontName='Helvetica-Bold',fontSize=9,leading=12,textColor=blue,spaceAfter=6)); s.add(ParagraphStyle(name='Body2',parent=s['BodyText'],fontSize=10.5,leading=15,textColor=ink,spaceAfter=7)); s.add(ParagraphStyle(name='Small',parent=s['BodyText'],fontSize=8.5,leading=11,textColor=muted)); s.add(ParagraphStyle(name='Card',parent=s['BodyText'],fontName='Helvetica-Bold',fontSize=11,leading=15,textColor=navy,alignment=TA_CENTER))
def footer(c,d):
 c.saveState(); c.setStrokeColor(colors.HexColor('#d8e3f0')); c.line(18*mm,14*mm,192*mm,14*mm); c.setFont('Helvetica',8); c.setFillColor(muted); c.drawString(18*mm,9*mm,'AutoEsperto | Funding brief | Documento di lavoro'); c.drawRightString(192*mm,9*mm,str(d.page)); c.restoreState()
def title(k,t,i=None):
 a=[Paragraph(k.upper(),s['Kicker']),Paragraph(t,s['H'])];
 if i:a.append(Paragraph(i,s['Body2']))
 return a
story=[Spacer(1,34*mm),Paragraph('AUTOESPERTO',s['CoverSub']),Spacer(1,6*mm),Paragraph("Decidere meglio<br/>prima di comprare<br/>un'auto usata.",s['CoverTitle']),Paragraph('Funding brief - proposta pre-seed - agosto 2026',s['CoverSub']),Spacer(1,22*mm)]
b=Table([[Paragraph('<b>Round di lavoro</b><br/><font size="20">EUR 250.000</font><br/>equity o convertible - runway 12 mesi',s['CoverSub'])]],colWidths=[174*mm],rowHeights=[31*mm]); b.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),colors.HexColor('#142943')),('BOX',(0,0),(-1,-1),.7,cyan),('LEFTPADDING',(0,0),(-1,-1),12),('TOPPADDING',(0,0),(-1,-1),8)])); story += [b,Spacer(1,35*mm),Paragraph('Dati di prodotto dal repository. Numeri di traction, ricavi e forecast: da validare.',s['Small']),PageBreak()]
story += title('01 · Problema','Il momento piu costoso e quello prima dell acquisto.','Comprare un usato richiede incrociare prezzo, affidabilita, manutenzione, documenti e condizioni. Le informazioni sono frammentate e poco comparabili. AutoEsperto riduce il rischio decisionale in pochi minuti.')
t=Table([[Paragraph('PREZZO',s['Card']),Paragraph('RISCHIO',s['Card']),Paragraph('AZIONE',s['Card'])],[Paragraph('Quanto vale davvero?',s['Body2']),Paragraph('Cosa devo verificare?',s['Body2']),Paragraph('Compro, tratto o evito?',s['Body2'])]],colWidths=[57*mm]*3); t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),light),('GRID',(0,0),(-1,-1),.5,colors.HexColor('#d8e3f0')),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('LEFTPADDING',(0,0),(-1,-1),8),('TOPPADDING',(0,0),(-1,-1),10)])); story += [t,Spacer(1,12*mm),Paragraph('<b>Insight:</b> il prodotto vende una decisione piu informata nel punto di massima intenzione.',s['Body2']),PageBreak()]
story += title('02 · Soluzione','Un copilota di acquisto, dalla targa al verdetto.','La piattaforma unisce dati di mercato, conoscenza dei modelli e AI in un flusso leggibile anche da chi non e esperto.')
t=Table([[Paragraph('1<br/><b>SCANSIONA</b><br/>targa, annuncio o foto',s['Card']),Paragraph('2<br/><b>CAPISCI</b><br/>prezzo, rischi, TCO',s['Card']),Paragraph('3<br/><b>DECIDI</b><br/>verdetto e prossima azione',s['Card'])]],colWidths=[58*mm]*3); t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),colors.HexColor('#f5f9ff')),('BOX',(0,0),(-1,-1),.7,blue),('INNERGRID',(0,0),(-1,-1),.5,colors.HexColor('#c5d7ef')),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('TOPPADDING',(0,0),(-1,-1),15),('BOTTOMPADDING',(0,0),(-1,-1),15)])); story += [t,Spacer(1,10*mm),Paragraph('<b>Core:</b> prezzo di mercato · affidabilita e manutenzione · Buy Score e verdetto operativo.<br/><b>Espansione:</b> AI Car Advisor · analisi foto/annuncio · Vehicle Passport · Buying Room.',s['Body2']),PageBreak()]
story += title('03 · Business model','Freemium B2C oggi. B2B ad alto margine domani.','I prezzi sono quelli presenti nel prodotto e vanno confermati prima del lancio commerciale.')
t=Table([[Paragraph('ENTRY',s['Card']),Paragraph('PREMIUM',s['Card']),Paragraph('B2B FUTURO',s['Card'])],[Paragraph('1 analisi gratuita<br/>acquisizione e prova',s['Body2']),Paragraph('EUR 5,99 report<br/>EUR 4,99/mese · EUR 41,90/anno',s['Body2']),Paragraph('Licenze/API per dealer, broker e media',s['Body2'])]],colWidths=[58*mm]*3); t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),navy),('TEXTCOLOR',(0,0),(-1,0),colors.white),('BACKGROUND',(0,1),(-1,1),light),('GRID',(0,0),(-1,-1),.5,colors.HexColor('#d8e3f0')),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('TOPPADDING',(0,0),(-1,-1),10),('BOTTOMPADDING',(0,0),(-1,-1),10)])); story += [t,Spacer(1,10*mm),Paragraph('<b>Metriche:</b> completamento scan · free-to-paid · CAC · retention · costo AI/report · margine lordo · report condivisi · piloti B2B.',s['Body2']),PageBreak()]
story += title('04 · Go-to-market','Catturare intenzione, poi trasformarla in fiducia.','Il wedge iniziale e il traffico organico ad alta intenzione: catalogo marca/modello/anno e guide editoriali collegati a un report condivisibile.')
t=Table([[Paragraph('ACQUISIZIONE',s['Card']),Paragraph('ATTIVAZIONE',s['Card']),Paragraph('ESPANSIONE',s['Card'])],[Paragraph('Catalogo SEO + guide<br/>partnership automotive',s['Body2']),Paragraph('Scan gratuito + report<br/>account e report salvati',s['Body2']),Paragraph('Premium + referral<br/>piloti dealer / API',s['Body2'])]],colWidths=[58*mm]*3); t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor('#e8f7fa')),('GRID',(0,0),(-1,-1),.5,colors.HexColor('#c5dfe4')),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('TOPPADDING',(0,0),(-1,-1),10),('BOTTOMPADDING',(0,0),(-1,-1),10)])); story += [t,Spacer(1,12*mm),Paragraph('<b>Due diligence:</b> il repository evidenzia catalogo ampio e 15 guide editoriali; non sono presenti metriche pubbliche verificate di utenti, ricavi o conversione.',s['Body2']),PageBreak()]
story += title('05 · Round proposto','EUR 250.000 per 12 mesi di prova misurabile.','Ipotesi pre-seed da validare con cap table, societa emittente, traction e forecast mensile.')
t=Table([[Paragraph('<b>AREA</b>',s['Body2']),Paragraph('<b>EUR</b>',s['Body2']),Paragraph('<b>RISULTATO</b>',s['Body2'])],[Paragraph('Prodotto, AI, qualita dati',s['Body2']),Paragraph('100.000',s['Body2']),Paragraph('report affidabili e provider',s['Body2'])],[Paragraph('Growth, SEO, contenuti',s['Body2']),Paragraph('62.500',s['Body2']),Paragraph('traffico e conversione',s['Body2'])],[Paragraph('Compliance e contratti dati',s['Body2']),Paragraph('50.000',s['Body2']),Paragraph('GDPR, licenze, audit',s['Body2'])],[Paragraph('Operations e B2B',s['Body2']),Paragraph('37.500',s['Body2']),Paragraph('piloti e supporto',s['Body2'])]],colWidths=[75*mm,30*mm,69*mm]); t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),navy),('TEXTCOLOR',(0,0),(-1,0),colors.white),('GRID',(0,0),(-1,-1),.4,colors.HexColor('#d8e3f0')),('TOPPADDING',(0,0),(-1,-1),7),('BOTTOMPADDING',(0,0),(-1,-1),7)])); story += [t,Spacer(1,9*mm),Paragraph('<b>Strumento consigliato ora:</b> equity o convertible. <b>Minibond piu avanti:</b> debito con rimborso, interessi e reporting.',s['Body2']),PageBreak()]
story += title('06 · Milestone e rischi','La raccolta compra evidenza, non solo sviluppo.','Ogni fase ha una prova concreta per decidere se accelerare.')
t=Table([[Paragraph('0-3 MESI',s['Card']),Paragraph('4-6 MESI',s['Card']),Paragraph('7-12 MESI',s['Card'])],[Paragraph('Hardening, analytics, provider dati, 100 beta user',s['Body2']),Paragraph('Catalogo sotto QA, primi paganti, baseline retention',s['Body2']),Paragraph('3-5 piloti B2B, partnership, prova subscription',s['Body2'])]],colWidths=[58*mm]*3); t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor('#fff3ea')),('GRID',(0,0),(-1,-1),.5,colors.HexColor('#ead5c5')),('VALIGN',(0,0),(-1,-1),'TOP'),('TOPPADDING',(0,0),(-1,-1),9),('BOTTOMPADDING',(0,0),(-1,-1),9)])); story += [t,Spacer(1,12*mm),Paragraph('<b>Guardrail:</b> ogni dato incerto deve essere marcato “Da verificare”. Prima del fundraising: privacy/legal review, contratti dati, cap table e forecast.',s['Body2']),PageBreak()]
story += title('07 · Investor ask','Costruiamo la categoria decision support per l usato.','Cerchiamo capitale e 2-3 partner pilota. Il prossimo incontro deve chiudere:')
t=Table([[Paragraph('<font color="#1d74f5" size="18"><b>01</b></font>',s['Body2']),Paragraph('Traction reale: utenti, scan, paganti, retention',s['Body2'])],[Paragraph('<font color="#1d74f5" size="18"><b>02</b></font>',s['Body2']),Paragraph('Pricing e margine: costo AI/provider per report',s['Body2'])],[Paragraph('<font color="#1d74f5" size="18"><b>03</b></font>',s['Body2']),Paragraph('Struttura: societa, cap table, strumento del round',s['Body2'])],[Paragraph('<font color="#1d74f5" size="18"><b>04</b></font>',s['Body2']),Paragraph('Distribuzione: primi partner e canali misurabili',s['Body2'])]],colWidths=[22*mm,152*mm]); t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),light),('GRID',(0,0),(-1,-1),.4,colors.white),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('LEFTPADDING',(0,0),(-1,-1),10),('TOPPADDING',(0,0),(-1,-1),9)])); story += [t,Spacer(1,16*mm),Paragraph('AutoEsperto',s['H']),Paragraph('Meno sorprese, piu decisioni informate.',s['Body2']),Spacer(1,13*mm),Paragraph('Documento di lavoro - agosto 2026 - preparato dal repository del prodotto',s['Small'])]
doc=SimpleDocTemplate(str(OUT),pagesize=A4,rightMargin=18*mm,leftMargin=18*mm,topMargin=17*mm,bottomMargin=19*mm,title='AutoEsperto Funding Pitch',author='AutoEsperto')
def first(c,d): c.saveState(); c.setFillColor(navy); c.rect(0,0,A4[0],A4[1],fill=1,stroke=0); c.restoreState(); footer(c,d)
doc.build(story,onFirstPage=first,onLaterPages=footer); print(OUT)
